#pragma once

#define FT_VOX_DEBUG					0
#define FT_VOX_LOG						0

#define FT_VOX_FULL_SCREEN				0
#define FT_VOX_ARRAY3_VALIDATION		0
#define FT_VOX_FORCE_EXIT				0
#define FT_VOX_LIGHT_COMPUTATION		0
#define FT_VOX_COLLISION_CHECK			0
#define FT_VOX_DYNAMIC_VISIBILITY   	0
#define FT_VOX_MULTILAYER_HEIGHT_NOISE	1

#define FT_VOX_SEED						21